import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://zajquppwybqpoldprone.supabase.com';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphanF1cHB3eWJxcG9sZHByb25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNDc4NTYsImV4cCI6MjA4MDgyMzg1Nn0.Yjh0TTTVjZmO4vNGAwZmmzCseVdv86RRRqAdfSMynFY.Yjh0TTTVjZmO4vNGAwZmmzCseVdv86RRRqAdfSMynFY.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphanF1cHB3eWJxcG9sZHByb25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNDc4NTYsImV4cCI6MjA4MDgyMzg1Nn0.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphanF1cHB3eWJxcG9sZHByb25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNDc4NTYsImV4cCI6MjA4MDgyMzg1Nn0.Yjh0TTTVjZmO4vNGAwZmmzCseVdv86RRRqAdfSMynFY;

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
